version: "3"
services: 
    frontend:
        container_name: frontend
        image: pdrojack/hackit:frontend
        build: ./frontend
        links: 
            - backend
        ports:
            - "80:80"

    backend:
        container_name: backend
        restart: always
        image: pdrojack/hackit:latest_backend
        build: ./backend
        ports: 
            - "9000:9000"